imports:
    - { resource: services/**.yaml }

services:
    Ibexa\Contracts\CorePersistence\Gateway\DoctrineSchemaMetadataRegistryInterface:
        alias: Ibexa\CorePersistence\Gateway\DoctrineSchemaMetadataRegistry

    Ibexa\CorePersistence\Gateway\DoctrineSchemaMetadataRegistry:
        arguments:
            $gateways: !tagged_iterator 'ibexa.core_persistence.doctrine_gateway'
